"""adding pictures to being table and gravatar to user

Revision ID: 1b5dfdb1f27b
Revises: dfa9f6b01b36
Create Date: 2018-10-23 13:40:25.118184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5dfdb1f27b'
down_revision = 'dfa9f6b01b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beings', sa.Column('picture', sa.String(length=72), nullable=True))
    op.drop_index('ix_beings_country', table_name='beings')
    op.drop_index('ix_stories_country', table_name='stories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stories_country', 'stories', ['country'], unique=False)
    op.create_index('ix_beings_country', 'beings', ['country'], unique=False)
    op.drop_column('beings', 'picture')
    # ### end Alembic commands ###
