"""updated Story, Being models to include MEANING instead of COUNTRY

Revision ID: 62513e2bc4ee
Revises: c31dd6a3f03b
Create Date: 2018-10-28 14:55:23.733192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62513e2bc4ee'
down_revision = 'c31dd6a3f03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beings', sa.Column('meaning', sa.String(length=60), nullable=False))
    op.drop_column('beings', 'country')
    op.add_column('stories', sa.Column('meaning', sa.String(length=60), nullable=False))
    op.drop_column('stories', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('country', sa.VARCHAR(length=60), nullable=False))
    op.drop_column('stories', 'meaning')
    op.add_column('beings', sa.Column('country', sa.VARCHAR(length=60), nullable=False))
    op.drop_column('beings', 'meaning')
    # ### end Alembic commands ###
