"""added source field for Story/Being

Revision ID: a5c5a27c4695
Revises: 1b5dfdb1f27b
Create Date: 2018-10-24 11:58:34.188510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c5a27c4695'
down_revision = '1b5dfdb1f27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beings', sa.Column('source', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_beings_source'), 'beings', ['source'], unique=False)
    op.add_column('stories', sa.Column('source', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_stories_source'), 'stories', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_source'), table_name='stories')
    op.drop_column('stories', 'source')
    op.drop_index(op.f('ix_beings_source'), table_name='beings')
    op.drop_column('beings', 'source')
    # ### end Alembic commands ###
