"""first migration after init

Revision ID: dfa9f6b01b36
Revises: 
Create Date: 2018-10-21 16:40:47.093665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa9f6b01b36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=72), nullable=True),
    sa.Column('psw_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_pic', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('beings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beings_category'), 'beings', ['category'], unique=False)
    op.create_index(op.f('ix_beings_country'), 'beings', ['country'], unique=False)
    op.create_index(op.f('ix_beings_name'), 'beings', ['name'], unique=True)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_category'), 'stories', ['category'], unique=False)
    op.create_index(op.f('ix_stories_country'), 'stories', ['country'], unique=False)
    op.create_index(op.f('ix_stories_title'), 'stories', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_title'), table_name='stories')
    op.drop_index(op.f('ix_stories_country'), table_name='stories')
    op.drop_index(op.f('ix_stories_category'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_beings_name'), table_name='beings')
    op.drop_index(op.f('ix_beings_country'), table_name='beings')
    op.drop_index(op.f('ix_beings_category'), table_name='beings')
    op.drop_table('beings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
