"""added source field default value

Revision ID: ff040d822cba
Revises: a5c5a27c4695
Create Date: 2018-10-24 12:16:34.378366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff040d822cba'
down_revision = 'a5c5a27c4695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_beings_source', table_name='beings')
    op.drop_index('ix_stories_source', table_name='stories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stories_source', 'stories', ['source'], unique=False)
    op.create_index('ix_beings_source', 'beings', ['source'], unique=False)
    # ### end Alembic commands ###
